name: Node.js Package

on:
  push:
    branches:
      - main
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm test

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
      - if: $GITHUB_ACTOR == kolbjornkelly
        run: git config user.email "kolbjorn.kelly@gmail.com"
        run: git config user.name "kolbjornkelly"
        run: npm version patch
      - if: $GITHUB_ACTOR == sarahjelle
        run: git config user.email "sarahj.98@hotmail.com"
        run: git config user.name "sarahjelle"
        run: npm version patch
      - if: $GITHUB_ACTOR == tengssimen
        run: git config user.email "simentengs@gmail.com"
        run: git config user.name "tengssimen"
        run: npm version patch
      - if: $GITHUB_ACTOR == sberbom
        run: git config user.email "sberbom@gmail.com"
        run: git config user.name "sberbom"
        run: npm version patch
      - run: npm ci
      - run: npm run build
      - run: npm publish ./dist
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
